### ISSUE TITLE
关于辅助线精确性问题建议方案

### ISSUE THREAD

**Issue by gorkys** [gorkys/vue-draggable-resizable-gorkys#25]
![image](https://user-images.githubusercontent.com/29664101/75848756-025e8480-5e1e-11ea-8c0c-225a2a3704ff.png)
### 问题一
> 关于辅助线不在控制点中间的问题

是因为基础导入的css导致控制点不在正中位置导致的，只要将
`handle-tm`,`handle-ml`,`handle-mr`,`handle-bm`四个中心控制点的样式进行覆盖。
例：
```css
.handle-tm {
  top: -5px;
  left: calc(50% - 4px);
  /*margin-left: -5px;*/
  cursor: n-resize;
}
```
### 问题二
> 关于未对齐时却出现辅助线的情况

因为元素大小的差值与`snapTolerance`所设值相近时导致的误差判断。
为了保证精确性，建议吸附功能与辅助线功能二选一。
`snapTolerance`值为1时，不会出现图中所见问题，所以当需求上`snapTolerance`值大于1时可选择关闭辅助线功能。

#### 另，如果有相关的修复方案可直接联系我或提交PR。
